version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    build: ./
    volumes:
      - ./tmp:/data:rw
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
