AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Datadog Billing Report'
Resources:
  DatadogReport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.datadog_handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: 'Datadog Billing Report'
      MemorySize: 256
      Timeout: 50
      Events:
        DatadogReport:
          Type: Api
          Properties:
            Path: /datadog_report
            Method: get
      Environment:
        Variables:
          APP_KEY: !Ref APP_KEY
          API_KEY: !Ref API_KEY
          SLACK_TOKEN: !Ref SLACK_TOKEN
          CHANNEL_ID: !Ref CHANNEL_ID
Parameters:
  APP_KEY:
    Default: ""
    Type: String
  API_KEY:
    Default: ""
    Type: String
  SLACK_TOKEN:
    Default: ""
    Type: String
  CHANNEL_ID:
    Default: ""
    Type: String
