
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Datadog Billing Report'
Resources:
  DatadogReport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.datadog_handler
      Runtime: nodejs8.10
      CodeUri: ./.build
      Description: 'Datadog Billing Report'
      MemorySize: 256
      Timeout: 50
      Events:
        DatadogReport:
          Type: Api
          Properties:
            Path: /datadog_report
            Method: get
      Environment:
        Variables:
          APP_KEY: !Ref AppKey
          API_KEY: !Ref ApiKey
          SLACK_TOKEN: !Ref SlackToken
          CHANNEL_ID: !Ref ChannelId
Parameters:
  AppKey:
    Type: String
  ApiKey:
    Type: String
  SlackToken:
    Type: String
  ChannelId:
    Type: String
