version: 2.1
jobs:
  build:
    docker:
      - image: node:8.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          command: npm test -- --ci
      - run:
          description: webpack build
          command: npm run build
      - store_test_results:
          path: reports/junit
